import csv
import time

def Attacklogs(message, sid):

    """ Function to record attack logs generated by various modules of the IPS """
    
    event_id = 0
    file = open('attackLogs.csv', mode='a+', newline='')
    
    try:
        file.seek(0)
        reader = csv.reader(file)
        rows = list(reader)
        
        if len(rows) > 1:
            last_row = rows[-1]
            event_id = int(last_row[0]) + 1
        
        writer = csv.writer(file)
        
        if file.tell() == 0:  # Check if the file is empty
            writer.writerow(['EventId', 'Timestamp', 'Message', 'Sid'])
        
        if sid is None:
            sid = "NULL"
        
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        writer.writerow([event_id, timestamp, message, sid])
    
    finally:
        file.close()
